#!/usr/bin/env -S ruby --jit

# frozen_string_literal: true
require_relative 'part1'
require_relative 'part2'

test = ARGV.first == "--test"

input_file = "#{test ? 'test_' : ''}input"

input = File.readlines(input_file).map do |line|
  line.gsub(/\n/, "")
end

Part1.run(input)
Part2.run(input)
